services:
    backend:
        build: .
        restart: always
        links:
            - elasticsearch:elasticsearch
        volumes:
            - data:/data
        healthcheck:
            test: 'curl -s -f "http://$${HOSTNAME}:8001/api/v1/healthcheck" >/dev/null || exit 1'
            interval: 60s
            timeout: 10s
    elasticsearch:
        image: elasticsearch:8.1.0
        restart: always
        environment:
            discovery.type: single-node
            network.host: _site_
            network.bind_host: _site_
            xpack.security.enabled: 'false'
        healthcheck:
            test: 'curl -s -f "http://$${HOSTNAME}:9200/_cat/health" >/dev/null || exit 1'
            interval: 60s
            timeout: 10s
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
    data: {}
    elasticsearch_data: {}
