services:
    backend:
        build: .
        restart: always
        environment:
            OS_URL: http://opensearch:9200
            FA_COOKIE_A: ${FA_COOKIE_A}
            FA_COOKIE_B: ${FA_COOKIE_B}
        links:
            - opensearch:opensearch
        volumes:
            - data:/data
        healthcheck:
            test: 'curl -s -f "http://$${HOSTNAME}:8001/api/v1/healthcheck" >/dev/null || exit 1'
            interval: 60s
            timeout: 10s
    opensearch:
        image: opensearchproject/opensearch:3.3.0
        restart: always
        ports:
            - 9200:9200
        environment:
            discovery.type: single-node
            network.host: _site_
            network.bind_host: _site_
            xpack.security.enabled: 'false'
        healthcheck:
            test: 'curl -s -f "http://$${HOSTNAME}:9200/_cat/health" >/dev/null || exit 1'
            interval: 60s
            timeout: 10s
        volumes:
            - opensearch_data:/usr/share/opensearch/data

volumes:
    data: {}
    opensearch_data: {}
