#!/bin/sh

set -e

cat << EOF > /etc/periodic/daily/looper
#!/bin/sh

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
cd /opt/app
export DOWNLOAD_PATH='${DOWNLOAD_PATH}'
export ES_URL='${ES_URL}'
export FA_COOKIE_A='${FA_COOKIE_A}'
export FA_COOKIE_B='${FA_COOKIE_B}'
s6-setuidgid '${PUID}:${PGID}' ./looper.sh
EOF

chmod +x /etc/periodic/daily/looper

exec crond -s -n
